version: '3.9'

services:
  dev-db:
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: zemfack
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: archi
  redis:
    image: redis:7
    ports:
      - 6379:6379
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081
